name: Test Code on Push
run-name: ${{ github.actor }} is running tests
on: [ push, workflow_dispatch ]

jobs:
  Test-On-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install
          npm install -g expo-cli
      
      - name: Run tests
        run: npm test

      - name: Generate coverage badge
        run: |
          COVERAGE=$(node -pe "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "lines: ${COVERAGE}%" > coverage-summary.md
